dist: jammy
language: python
sudo: required
os:
  - linux
services:
  - postgresql
python:
  - "3.11"
before_install:
  - sudo apt-get update
install:
  - psql -p 5432 -c 'create database travis_ci_test;' -U postgres
  - pip install -r requirements-dev.txt
  - source travis_env.sh
  - python manage.py migrate
script:
  - source travis_env.sh
  - python manage.py test
  - black --check .
