language: python
sudo: required
os:
  - linux
services:
  - postgresql
addons:
  postgresql: "11"
  apt:
    packages:
    - postgresql-11
    - postgresql-client-11
python:
  - "3.7.3"
install:
  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  - sudo service postgresql restart 11
  - psql -p 5433 -c 'create database travis_ci_test;' -U postgres
  - pip install -r requirements-dev.txt
  - source travis_env.sh
  - python manage.py migrate
script:
  - source travis_env.sh
  - python manage.py test
