language: python
sudo: required
os:
  - linux
python:
  - "3.10"
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - pip install --upgrade setuptools==70.0.0
  - pip install --upgrade pip
  - pip install -r requirements-dev.txt
  - source travis_env.sh
  - python manage.py migrate
script:
  - source travis_env.sh
  - python manage.py test
  - black --check .
