language: python
sudo: required
os:
  - linux
services:
  - postgresql
addons:
  postgresql: "11"
  apt:
    packages:
    - postgresql-11
    - postgresql-client-11
python:
  - "3.8"
before_install:
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-11 postgresql-client-11
  - sudo cp /etc/postgresql/11/main/pg_hba.conf
  - sudo service postgresql restart 11
install:
  - psql -p 5433 -c 'create database travis_ci_test;' -U postgres
  - pip install --upgrade setuptools==70.0.0
  - pip install --upgrade pip
  - pip install -r requirements-dev.txt
  - source travis_env.sh
  - python manage.py migrate
script:
  - source travis_env.sh
  - python manage.py test
  - black --check .
