language: python
sudo: required
os:
  - linux
services:
  - postgresql
addons:
  postgresql: "13"
  apt:
    packages:
    - postgresql-13
    - postgresql-client-13
env:
  global:
    - PGPORT=5433
python:
  - "3.8"
before_install:
  - sudo apt-get update
  # Use trust instead of peer authentication:
  - >-
    sudo sed -i
    -e '/local.*peer/s/postgres/all/'
    -e 's/peer\|md5/trust/g'
    /etc/postgresql/13/main/pg_hba.conf
  - sudo service postgresql@13-main restart
install:
  - psql -p 5433 -c 'create database travis_ci_test;' -U postgres
  - pip install --upgrade setuptools==70.0.0
  - pip install --upgrade pip
  - pip install -r requirements-dev.txt
  - source travis_env.sh
  - python manage.py migrate
script:
  - source travis_env.sh
  - python manage.py test
  - black --check .
