language: python
addons:
  postgresql: "11"
  apt:
    packages:
    - postgresql-11
    - postgresql-client-11
python:
  - "3.7.3"
install:
  - pip install -r requirements-dev.txt
  - python manage.py migrate
script:
  - source travis_env.sh 
  - python manage.py test
