# Generated by Django 2.2.28 on 2026-02-10 15:09

from django.db import migrations, models
import django.db.models.deletion
import file_manager.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("file_system", "0047_auto_20260210_0939"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseModel",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_date", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SampleProviderJob",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="file_manager.BaseModel",
                    ),
                ),
                ("sample_id", models.CharField(db_index=True, max_length=100, unique=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "SCHEDULED"), (1, "IN_PROGRESS"), (2, "COMPLETED")],
                        db_index=True,
                        default=file_manager.models.FileProviderStatus(0),
                    ),
                ),
                ("total_files", models.IntegerField(default=0)),
                ("completed_files", models.IntegerField(default=0)),
            ],
            bases=("file_manager.basemodel",),
        ),
        migrations.CreateModel(
            name="FileProviderJob",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="file_manager.BaseModel",
                    ),
                ),
                ("original_path", models.CharField(db_index=True, max_length=1500)),
                ("staged_path", models.CharField(db_index=True, max_length=1500)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "SCHEDULED"), (1, "IN_PROGRESS"), (2, "COMPLETED")],
                        db_index=True,
                        default=file_manager.models.FileProviderStatus(0),
                    ),
                ),
                (
                    "file_object",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="file_system.File"),
                ),
            ],
            bases=("file_manager.basemodel",),
        ),
        migrations.CreateModel(
            name="CleanupFileJob",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="file_manager.BaseModel",
                    ),
                ),
                ("original_path", models.CharField(db_index=True, max_length=1500)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "SCHEDULED"), (1, "IN_PROGRESS"), (2, "COMPLETED")],
                        db_index=True,
                        default=file_manager.models.FileProviderStatus(0),
                    ),
                ),
                ("cleanup_date", models.DateField(db_index=True)),
                (
                    "file_object",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="file_system.File"),
                ),
            ],
            bases=("file_manager.basemodel",),
        ),
        migrations.AddConstraint(
            model_name="fileproviderjob",
            constraint=models.UniqueConstraint(fields=("file_object",), name="unique_file_provider_job_per_file"),
        ),
    ]
