# Generated by Django 2.2.28 on 2026-03-17 18:36

from django.db import migrations, models
import file_manager.models


class Migration(migrations.Migration):

    dependencies = [
        ("file_manager", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="fileproviderjob",
            name="unique_file_provider_job_per_file",
        ),
        migrations.AlterField(
            model_name="cleanupfilejob",
            name="status",
            field=models.IntegerField(
                choices=[(0, "SCHEDULED"), (1, "IN_PROGRESS"), (2, "COMPLETED"), (3, "FAILED")],
                db_index=True,
                default=file_manager.models.FileProviderStatus(0),
            ),
        ),
        migrations.AlterField(
            model_name="fileproviderjob",
            name="status",
            field=models.IntegerField(
                choices=[(0, "SCHEDULED"), (1, "IN_PROGRESS"), (2, "COMPLETED"), (3, "FAILED")],
                db_index=True,
                default=file_manager.models.FileProviderStatus(0),
            ),
        ),
        migrations.AlterField(
            model_name="sampleproviderjob",
            name="status",
            field=models.IntegerField(
                choices=[(0, "SCHEDULED"), (1, "IN_PROGRESS"), (2, "COMPLETED"), (3, "FAILED")],
                db_index=True,
                default=file_manager.models.FileProviderStatus(0),
            ),
        ),
        migrations.AddConstraint(
            model_name="fileproviderjob",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    status__in=[file_manager.models.FileProviderStatus(0), file_manager.models.FileProviderStatus(1)]
                ),
                fields=("file_object",),
                name="unique_active_file_provider_job_per_file",
            ),
        ),
    ]
