# Generated by Django 6.0.4 on 2026-06-10 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_manager", "0002_update_file_provider_job_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileproviderjob",
            name="sample_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="file_jobs",
                to="file_manager.sampleproviderjob",
            ),
        ),
    ]
