# Generated by Django 2.2.28 on 2023-11-01 16:54

from django.db import migrations, models
import study.models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_auto_20230608_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobgroupwatcher',
            name='status',
            field=models.IntegerField(choices=[(0, 'WAITING'), (1, 'COMPLETED')], db_index=True, default=study.models.JobGroupWatcherStatus(0)),
        ),
    ]
