# Generated by Django 2.2.24 on 2021-09-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0010_jobgroupnotifier_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobgroupnotifier',
            name='PI',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jobgroupnotifier',
            name='assay',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jobgroupnotifier',
            name='investigator',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
