# Generated by Django 2.2.24 on 2021-09-14 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0012_auto_20210913_0518'),
        ('notifier', '0006_remove_jobgroup_jira_id'),
    ]

    operations = [
    ]
