# Generated by Django 2.2.28 on 2024-07-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0014_auto_20211005_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobgroupnotifier',
            name='PI',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='jobgroupnotifier',
            name='investigator',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
