# Generated by Django 2.2.24 on 2022-05-09 11:18

import beagle_etl.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beagle_etl", "0031_smilemessage_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smilemessage",
            name="status",
            field=models.IntegerField(
                choices=[(0, "PENDING"), (1, "COMPLETED"), (2, "NOT_SUPPORTED")],
                db_index=True,
                default=beagle_etl.models.SmileMessageStatus(0),
            ),
        ),
    ]
