# Generated by Django 2.2.28 on 2023-07-11 14:28

import beagle_etl.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beagle_etl", "0036_auto_20230308_0917"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smilemessage",
            name="status",
            field=models.IntegerField(
                choices=[(0, "PENDING"), (1, "COMPLETED"), (2, "NOT_SUPPORTED"), (3, "FAILED")],
                db_index=True,
                default=beagle_etl.models.SmileMessageStatus(0),
            ),
        ),
    ]
