pipeline {
  agent any
  stages {
      stage('Deploy to Stage') {
        steps {
        build job: "beagle-deploy/develop_mock", parameters: [[$class: 'StringParameterValue', name: 'SERVER', value: "STAGE"]],  propagate: true, wait: true
        }
      }
      stage('Run integration tests') {
        steps {
        sshagent(credentials: ['a4d999a5-6318-4659-83be-3f148a5490ca']) {
          sh 'ssh  -o StrictHostKeyChecking=no -o UserKnownHostsFile=/juno/work/ci/jenkins/known_hosts voyager@silo.mskcc.org "export BUILD_NUMBER=${env.BUILD_NUMBER} && export BUILD_URL=${env.BUILD_URL} && cd /srv/services/staging_voyager/beagle/code/beagle && source /juno/work/ci/jenkins/lsf.sh && source /srv/services/staging_voyager/beagle/config/config.sh && source /juno/work/ci/voyager_continous_deployment/staging/test_env.sh && singularity run instance://staging_beagle python3 manage.py test integration_tests"'
        }
        }
     }
  }
  post {
        failure {
        slackSend channel: '#robot-house',
                  color: 'bad',
                  message: "The pipeline ${currentBuild.fullDisplayName} failed."
    }
        success {
        slackSend channel: '#robot-house',
                  color: 'good',
                  message: "The pipeline ${currentBuild.fullDisplayName} completed successfully."
    }

  }
}
