# This file OVERRIDES docker-compose.base.yml
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    # Overriding the command to use runserver
    command: python3 manage.py runserver 0:5007 --noreload
    working_dir: /app/src
    volumes:
      - ./src:/app/src:z
    environment:
      - PYTHONPATH=/app/src
      - BEAGLE_RABBITMQ_URL=${BEAGLE_RABBITMQ_URL}:${BEAGLE_RABBITMQ_PORT}
    ports:
      - "5007:5007"

  worker:
    build:
      context: .
    working_dir: /app/src
    volumes:
      - ./src:/app/src:z
    environment:
      - PYTHONPATH=/app/src
      - BEAGLE_RABBITMQ_URL=${BEAGLE_RABBITMQ_URL}:${BEAGLE_RABBITMQ_PORT}

  beat:
    build:
      context: .
    working_dir: /app/src
    volumes:
      - ./src:/app/src:z
    environment:
      - PYTHONPATH=/app/src
      - BEAGLE_RABBITMQ_URL=${BEAGLE_RABBITMQ_URL}:${BEAGLE_RABBITMQ_PORT}

  db:
    # Adding development ports so you can connect via DBeaver/Datagrip
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data:z

  rabbitmq:
    environment:
      - RABBITMQ_DEFAULT_USER=${BEAGLE_RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${BEAGLE_RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"

  memcached:
    ports:
      - "11211:11211"

volumes:
  pgdata:
