services:
  api:
    init: true
    image: mskcc/beagle:2.1.0
    networks:
      - beagle_net
    build:
      context: .
    working_dir: /app
    command: python manage.py runserver 0:5007 --noreload
    volumes:
      - ./src:/app:z
    env_file: .env.dev
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - BEAGLE_DB_URL=${BEAGLE_DB_URL}
      - BEAGLE_DB_NAME=${BEAGLE_DB_NAME}
      - BEAGLE_DB_USERNAME=${BEAGLE_DB_USERNAME}
      - BEAGLE_DB_PASSWORD=${BEAGLE_DB_PASSWORD}
      - BEAGLE_RABBITMQ_USERNAME=${BEAGLE_RABBITMQ_USERNAME}
      - BEAGLE_RABBITMQ_PASSWORD=${BEAGLE_RABBITMQ_PASSWORD}
      - BEAGLE_RABBITMQ_PORT=${BEAGLE_RABBITMQ_PORT}
      - BEAGLE_RABBITMQ_URL=${BEAGLE_RABBITMQ_URL}:${BEAGLE_RABBITMQ_PORT}
      - CELERY_BROKER_URL=amqp://${BEAGLE_DB_NAME}:${BEAGLE_USER_NAME}@{BEAGLE_RABBITMQ_URL}//
      - BEAGLE_RUNNER_QUEUE=${BEAGLE_RUNNER_QUEUE}
    ports:
      - "5007:5007"
    depends_on:
      - db
      - rabbitmq
      - memcached

  worker:
    build:
      context: .
    working_dir: /app
    networks:
      - beagle_net
    command: celery -A beagle_etl worker -l info
    volumes:
      - ./src:/app:z
    env_file: .env.dev
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - BEAGLE_DB_NAME=${BEAGLE_DB_NAME}
      - BEAGLE_DB_USERNAME=${BEAGLE_DB_USERNAME}
      - BEAGLE_DB_PASSWORD=${BEAGLE_DB_PASSWORD}
      - BEAGLE_RABBITMQ_USERNAME=${BEAGLE_RABBITMQ_USERNAME}
      - BEAGLE_RABBITMQ_PASSWORD=${BEAGLE_RABBITMQ_PASSWORD}
      - BEAGLE_RABBITMQ_PORT=${BEAGLE_RABBITMQ_PORT}
      - BEAGLE_RABBITMQ_URL=${BEAGLE_RABBITMQ_URL}:${BEAGLE_RABBITMQ_PORT}
      - CELERY_BROKER_URL=amqp://${BEAGLE_DB_NAME}:${BEAGLE_USER_NAME}@{BEAGLE_RABBITMQ_URL}//
    depends_on:
      - rabbitmq
      - db

  beat:
    build:
      context: .
    working_dir: /app
    networks:
      - beagle_net
    command: celery -A beagle_etl beat -l info
    volumes:
      - ./src:/app:z
    env_file: .env.dev
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - BEAGLE_DB_NAME=${BEAGLE_DB_NAME}
      - BEAGLE_DB_USERNAME=${BEAGLE_DB_USERNAME}
      - BEAGLE_DB_PASSWORD=${BEAGLE_DB_PASSWORD}
      - BEAGLE_RABBITMQ_USERNAME=${BEAGLE_RABBITMQ_USERNAME}
      - BEAGLE_RABBITMQ_PASSWORD=${BEAGLE_RABBITMQ_PASSWORD}
      - BEAGLE_RABBITMQ_PORT=${BEAGLE_RABBITMQ_PORT}
      - BEAGLE_RABBITMQ_URL=${BEAGLE_RABBITMQ_URL}:${BEAGLE_RABBITMQ_PORT}
      - CELERY_BROKER_URL=amqp://${BEAGLE_DB_NAME}:${BEAGLE_USER_NAME}@{BEAGLE_RABBITMQ_URL}//
    depends_on:
      - rabbitmq
      - db

  db:
    image: postgres:16
    working_dir: /app
    networks:
      - beagle_net
    env_file: .env.dev
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - BEAGLE_DB_NAME=${BEAGLE_DB_NAME}
      - BEAGLE_DB_USERNAME=${BEAGLE_DB_USERNAME}
      - BEAGLE_DB_PASSWORD=${BEAGLE_DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data:z
      - .:/app:z

  rabbitmq:
    image: rabbitmq:3-management
    networks:
      - beagle_net
    env_file: .env.dev
    environment:
      - RABBITMQ_DEFAULT_USER=${BEAGLE_RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${BEAGLE_RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"  # management UI

  memcached:
    image: memcached:1.6
    networks:
      - beagle_net
    ports:
      - "11211:11211"

volumes:
  pgdata:

networks:
  beagle_net:
