# Generated by Django 2.2.28 on 2024-11-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_system", "0040_auto_20230901_2152"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="available",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
