# Generated by Django 2.2.2 on 2019-07-03 20:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('file_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='metadata',
        ),
        migrations.CreateModel(
            name='FileMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField()),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_system.File')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CohortMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField()),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_system.Cohort')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
