# Generated by Django 2.2.2 on 2019-07-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_system', '0002_auto_20190703_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='version',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
