# Generated by Django 2.2.2 on 2019-07-25 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_system', '0003_file_version'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cohort',
            new_name='FileGroup',
        ),
        migrations.RenameModel(
            old_name='CohortMetadata',
            new_name='FileGroupMetadata',
        ),
        migrations.AlterField(
            model_name='file',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='file_system.Sample'),
        ),
    ]
