# Generated by Django 2.2.2 on 2019-07-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_system', '0003_auto_20190730_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='lane',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='pair_end',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
