# Generated by Django 2.2.2 on 2019-08-14 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_system', '0004_auto_20190730_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='lane',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='pair_end',
            field=models.IntegerField(null=True),
        ),
    ]
