# Generated by Django 2.2.2 on 2019-07-25 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file_system', '0004_auto_20190725_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='version',
        ),
        migrations.AddField(
            model_name='filemetadata',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
