# Generated by Django 2.2.2 on 2019-12-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_system', '0009_filerunmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.CharField(max_length=1500, unique=True),
        ),
    ]
