# Generated by Django 2.2.8 on 2019-12-09 16:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_system', '0010_auto_20191202_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetype',
            name='valid_extensions',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
