# Generated by Django 2.2.9 on 2020-04-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_system', '0013_auto_20200127_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='checksum',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
