# Generated by Django 2.2.11 on 2020-06-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_system', '0014_file_checksum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.CharField(db_index=True, max_length=1500, unique=True),
        ),
    ]
