# Generated by Django 2.2.10 on 2020-06-13 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_system', '0015_auto_20200612_2005'),
        ('file_system', '0015_auto_20200608_0412'),
    ]

    operations = [
    ]
