# Generated by Django 2.2.11 on 2020-10-06 22:07

from django.db import migrations


def add_samples(apps, schema_editor):
    File = apps.get_model('file_system', 'File')
    FileGroup = apps.get_model('file_system', 'FileGroup')
    Sample = apps.get_model('file_system', 'Sample')

    try:
        fg = FileGroup.objects.get(name="LIMS")
    except FileGroup.DoesNotExist:
        return

    files = File.objects.filter(file_group=fg).all()
    for f in files:
        metadata = f.filemetadata_set.order_by('-created_date').first().metadata
        igo_id = metadata.get('sampleId')
        try:
            sample = Sample.objects.get(sample_id=igo_id)
        except Sample.DoesNotExist:
            sample = Sample.objects.create(sample_id=igo_id)
        f.sample = sample
        f.save()


class Migration(migrations.Migration):

    dependencies = [
        ('file_system', '0020_auto_20201006_1732'),
    ]

    operations = [
        migrations.RunPython(add_samples)
    ]
