# Generated by Django 2.2.24 on 2022-04-18 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_system', '0029_auto_20220218_1006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'select_on_save': True},
        ),
    ]
