# Generated by Django 2.2.28 on 2022-11-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_system', '0030_auto_20220418_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.CharField(db_index=True, max_length=1500),
        ),
    ]
