# Generated by Django 2.2.28 on 2022-12-22 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("file_system", "0034_auto_20221122_0833"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="request",
            name="lab_head_email",
        ),
    ]
