# Generated by Django 2.2.28 on 2023-03-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_system", "0036_auto_20221227_1919"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="samples",
            field=models.ManyToManyField(related_name="samples", to="file_system.Sample"),
        ),
    ]
