# Generated by Django 2.2.28 on 2023-03-08 08:20

from django.db import migrations


def update_samples(apps, schema_editor):
    File = apps.get_model("file_system", "File")
    for f in File.objects.all():
        if f.sample:
            f.samples.add(f.sample)
        else:
            print(f"File {f.pk}:{f.path} doesn't have sample set")


class Migration(migrations.Migration):

    dependencies = [
        ("file_system", "0037_file_samples"),
    ]

    operations = [
        migrations.RunPython(update_samples),
    ]
