# Generated by Django 2.2.28 on 2023-04-24 11:51

from django.db import migrations
from django.conf import settings


def populate_patient_request_sample(apps, schema_editor):
    File = apps.get_model("file_system", "File")
    files = File.objects.filter(file_group=settings.IMPORT_FILE_GROUP)
    for f in files:
        metadata = f.filemetadata_set.filter(latest=True).first()
        if metadata:
            if not f.request_id:
                request_id = metadata.metadata.get(settings.REQUEST_ID_METADATA_KEY, "")
                f.request_id = request_id
            if not f.samples:
                sample_id = metadata.metadata.get(settings.SAMPLE_ID_METADATA_KEY, "")
                if sample_id not in f.samples:
                    f.samples.append(sample_id)
            if not f.patient_id:
                patient_id = metadata.metadata.get(settings.PATIENT_ID_METADATA_KEY, "")
                f.patient_id = patient_id
            f.save()


def revert(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('file_system', '0037_auto_20230424_0743'),
    ]

    operations = [
        migrations.RunPython(populate_patient_request_sample, reverse_code=revert),
    ]
