# Generated by Django 2.2.28 on 2023-04-10 06:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_system', '0037_auto_20230410_0634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='request',
        ),
        migrations.AddField(
            model_name='sample',
            name='request_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='patient',
            name='samples',
        ),
        migrations.AddField(
            model_name='patient',
            name='samples',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None),
        ),
    ]
