# Generated by Django 2.2.28 on 2024-07-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_system", "0040_auto_20230901_2152"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="missing",
            field=models.BooleanField(default=False),
        ),
    ]
