# Generated by Django 2.2.28 on 2024-12-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_system", "0041_file_available"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="sample",
        )
    ]
