# Generated by Django 2.2.28 on 2025-04-18 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("file_system", "0044_auto_20241224_1254"),
        ("file_system", "0042_auto_20250418_1806"),
    ]

    operations = []
