# Generated by Django 2.2.28 on 2025-12-17 14:37

from django.db import migrations
from beagle import settings
from file_system.helper.flatten_patient_aliases import update_patient_aliases


def migrate_patient_aliases(apps, schema_editor):
    FileRepository = apps.get_model("file_system", "FileRepository")
    Fqs = FileRepository.objects.filter(
        file_group=settings.IMPORT_FILE_GROUP
    )
    for f in Fqs:
        metadata = f.metadata or {}

        if update_patient_aliases(metadata):
            f.metadata = metadata
            f.save(update_fields=["metadata"])


class Migration(migrations.Migration):

    dependencies = [
        ("file_system", "0045_merge_20250418_1834"),
    ]

    operations = [migrations.RunPython(migrate_patient_aliases)]
