# Generated by Django 2.2.28 on 2025-12-17 14:37

from django.db import migrations
from beagle import settings
from file_system.helper.flatten_patient_aliases import update_patient_aliases


def migrate_patient_aliases(apps, schema_editor):
    FileMetadata = apps.get_model("file_system", "FileMetadata")
    Fqs = FileMetadata.objects.filter(file__file_group=settings.IMPORT_FILE_GROUP)
    for fm in Fqs:
        metadata = fm.metadata or None
        if metadata and update_patient_aliases(metadata):
            fm.metadata = metadata
            fm.save(update_fields=["metadata"])


class Migration(migrations.Migration):

    dependencies = [
        ("file_system", "0045_merge_20250418_1834"),
    ]

    operations = [migrations.RunPython(migrate_patient_aliases)]
