# Generated by Django 2.2.28 on 2026-02-10 14:39

from django.db import migrations, models


def populate_original_paths(apps, schema_editor):
    File = apps.get_model("file_system", "File")
    files = File.objects.all()
    for f in files:
        try:
            pass
        except Exception:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ("file_system", "0046_migrate_patient_aliases"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="original_path",
            field=models.CharField(default="", max_length=1500),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="ImportMetadata",
        ),
    ]
