#!/bin/bash
set -euo pipefail

# script for sanitizing the contents of a file to remove unwanted patterns (such as sample ID's)
#
# requires file "patterns.tsv"
# which should be in the format of:
#
# <old_pattern>\t<new_pattern>
#
# which can be generated by 1) using the included './get_fields_to_sanitize.sh' script to get the starting fields from the FileMetadata JSON
# 2) copy/paste those values into a new "patterns.tsv" file in this directory (can do this in nano from command line)
# 3) open the "patterns.tsv" in Excel and fill in the new patterns in the adjacent column (can use generate_cmo_id.py to make fake CMO id's quickly)
# 4) do not save the updated "patterns.tsv" file in Excel, but instead highlight & copy both columns, then open "patterns.tsv" in Atom and paste the full contents there, they will come out TSV formatted
#
# USAGE:
# ./sanitize.sh filemetadata.json

input_file="${1}"
patterns_file="patterns.tsv"

# make sure patterns file exists
[ ! -e "${patterns_file}" ] && echo "ERROR: file does not exist: ${patterns_file}" && exit 1

# make sure 'patterns' file doesnt have less than 1 line
[ "$(cat "${patterns_file}" | wc -l)" -lt "1" ] && echo "ERROR: Not enough lines in patterns file ${patterns_file}" &&  exit 1

# need to clean the 'patterns' file; remove Windows carriage returns, empty lines
perl -pi -e 's|\r\n$|\n|g' "${patterns_file}"
perl -pi -e 's|^[[:space:]]*$||g' "${patterns_file}"

# create regex pattern for replacement
# need to sort patterns from longest to shortest
patterns_str="$(cat ${patterns_file} | awk '{ print length($1), $0 }' | sort -k1,1nr | cut -d ' ' -f2- | sed -e '/^$/d' -e 's|[[:space:]]|/|g' -e 's|^|s/|g' -e 's|$|/g;|g' | tr '\n' ' ')"

# do the actual string replacement in the file
perl -pi -e "${patterns_str}" "${input_file}"
