# Generated by Django 2.2.2 on 2019-08-28 03:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='value',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
