# Generated by Django 2.2.2 on 2019-09-03 21:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0002_auto_20190828_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='execution_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='job_statuses',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
