# Generated by Django 2.2.2 on 2019-09-24 22:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0003_auto_20190903_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionEvents',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('execution_id', models.UUIDField()),
                ('name', models.CharField(max_length=100)),
                ('job_status', models.CharField(max_length=30)),
                ('message', models.CharField(max_length=1000)),
                ('err_file_path', models.CharField(max_length=200)),
                ('outputs', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
