# Generated by Django 2.2.2 on 2019-10-29 18:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_system', '0007_remove_filegroup_metadata'),
        ('runner', '0005_auto_20191028_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='port',
            name='secondary_files',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='port',
            name='schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FileJobTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_system.File')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runner.Run')),
            ],
        ),
    ]
