# Generated by Django 2.2.2 on 2019-10-29 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0006_auto_20191029_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='port',
            name='required',
        ),
    ]
