# Generated by Django 2.2.2 on 2019-12-05 21:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0009_operatorerrors'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='output_metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
