# Generated by Django 2.2.8 on 2020-01-08 22:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0010_run_output_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='tags',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
