# Generated by Django 2.2.8 on 2020-01-17 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0011_auto_20200106_2113'),
        ('runner', '0012_auto_20200110_1936'),
    ]

    operations = [
    ]
