# Generated by Django 2.2.8 on 2020-02-04 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0014_port_files'),
        ('runner', '0013_merge_20200117_2050'),
    ]

    operations = [
    ]
