# Generated by Django 2.2.8 on 2020-02-04 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0015_auto_20200124_2041'),
        ('runner', '0015_merge_20200204_1905'),
    ]

    operations = [
    ]
