# Generated by Django 2.2.9 on 2020-02-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0016_merge_20200204_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='pipeline_type',
            field=models.IntegerField(choices=[(0, 'CWL')], default=0),
            preserve_default=False,
        ),
    ]
