# Generated by Django 2.2.9 on 2020-02-10 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beagle_etl', '0013_auto_20200210_1902'),
        ('runner', '0016_merge_20200204_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beagle_etl.Operator'),
        ),
    ]
