# Generated by Django 2.2.9 on 2020-02-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0017_pipeline_pipeline_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
