# Generated by Django 2.2.9 on 2020-02-27 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0022_auto_20200225_1336'),
        ('runner', '0022_auto_20200225_0414'),
    ]

    operations = [
    ]
