# Generated by Django 2.2.9 on 2020-03-31 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0024_auto_20200316_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='output_directory',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
