# Generated by Django 2.2.9 on 2020-04-09 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0025_run_output_directory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operatorrun',
            name='trigger',
        ),
    ]
