# Generated by Django 2.2.11 on 2020-06-17 17:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0029_auto_20200612_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='message',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
