# Generated by Django 2.2.11 on 2020-06-17 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0030_auto_20200616_1320'),
        ('runner', '0030_run_message'),
    ]

    operations = [
    ]
