# Generated by Django 2.2.11 on 2020-10-13 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0034_pipeline_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='resume',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
