# Generated by Django 2.2.11 on 2020-12-02 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0036_run_samples'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorrun',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='runner.OperatorRun'),
        ),
    ]
