# Generated by Django 2.2.11 on 2020-12-02 18:06

from django.db import migrations


from runner.run.objects.cwl.cwl_run_object import CWLRunObject
from runner.run.processors.file_processor import FileProcessor


def populate_run_samples(apps, _):
    Run = apps.get_model('runner', 'Run')
    for run in Run.objects.all():
        samples = set()
        try:
            run_obj = CWLRunObject.from_db(run.id)
        except Exception as e:
            print("Run %s can't be migrated" % str(run.id))
        for p in run_obj.inputs:
            for f in p.files:
                file_obj = FileProcessor.get_file_obj(f)
                if file_obj.sample:
                    samples.add(file_obj.sample)
        run_obj.samples = list(samples)
        run_obj.to_db()


def revert_migration(apps, _):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0037_operatorrun_parent'),
    ]

    operations = [
        migrations.RunPython(populate_run_samples, reverse_code=revert_migration)
    ]
