# Generated by Django 2.2.13 on 2020-12-21 21:55

from django.db import migrations, models
import runner.models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0039_set_operator_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatorrun',
            name='status',
            field=models.IntegerField(choices=[(0, 'CREATING'), (1, 'READY'), (2, 'RUNNING'), (3, 'FAILED'), (4, 'COMPLETED'), (5, 'ABORTED')], db_index=True, default=runner.models.RunStatus(0)),
        ),
        migrations.AlterField(
            model_name='run',
            name='status',
            field=models.IntegerField(choices=[(0, 'CREATING'), (1, 'READY'), (2, 'RUNNING'), (3, 'FAILED'), (4, 'COMPLETED'), (5, 'ABORTED')], db_index=True),
        ),
    ]
