# Generated by Django 2.2.11 on 2020-12-02 18:06

from django.db import migrations


from runner.models import Run
from runner.tasks import check_status_on_ridgeback, update_commandline_job_status

def populate_job_statuses(apps, _):
    for single_run in Run.objects.all():
        try:
            if not single_run.job_statuses or True:
                if single_run.execution_id:
                    remote_status = check_status_on_ridgeback(single_run.execution_id)
                    update_commandline_job_status(single_run, remote_status['commandlinetooljob_set'])
        except Exception as e:
            print("Run %s could not update job statuses"  % str(single_run.id))


def revert_migration(apps, _):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0040_auto_20201221_1655'),
    ]

    operations = [
        migrations.RunPython(populate_job_statuses, reverse_code=revert_migration)
    ]
