# Generated by Django 2.2.11 on 2020-12-02 18:06

from django.db import migrations


from runner.models import Run
from runner.tasks import check_status_on_ridgeback, update_commandline_job_status

def populate_job_info(apps, _):
    for single_run in Run.objects.all():
        try:
            if not single_run.job_statuses:
                if single_run.execution_id:
                    remote_status = check_status_on_ridgeback(single_run.execution_id)
                    update_commandline_job_status(single_run, remote_status['commandlinetooljob_set'])
                    if remote_status['started'] and not single_run.started:
                        single_run.started = remote_status['started']
                    if remote_status['submitted'] and not single_run.submitted:
                        single_run.submitted = remote_status['submitted']
                    single_run.save()
        except Exception as e:
            print("Run %s could not update job statuses"  % str(single_run.id))


def revert_migration(apps, _):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0041_auto_20210112_1400'),
    ]

    operations = [
        migrations.RunPython(populate_job_info, reverse_code=revert_migration)
    ]
