# Generated by Django 2.2.13 on 2021-03-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0042_populate_job_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='memlimit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='walltime',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
