# Generated by Django 2.2.13 on 2021-02-03 18:11

from django.db import migrations, models
import runner.models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0042_populate_job_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorrun',
            name='state',
            field=models.IntegerField(choices=[(0, 'OPEN'), (1, 'LOCKED')], db_index=True, default=runner.models.RunState(0)),
        ),
    ]
