# Generated by Django 2.2.13 on 2021-04-07 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0044_auto_20210316_1557'),
        ('runner', '0043_auto_20210330_0928'),
    ]

    operations = [
    ]
