# Generated by Django 2.2.13 on 2021-02-03 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0044_auto_20210203_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='state',
        ),
    ]
