# Generated by Django 2.2.13 on 2021-05-25 19:13

from django.db import migrations, models
from runner.models import ProtocolType, Pipeline


def populate_pipeline_type(apps, _):
    pipelines = Pipeline.objects.all()
    for pipeline in pipelines:
        if pipeline.entrypoint.endswith('.cwl'):
            pipeline.pipeline_type = ProtocolType.CWL
            pipeline.save()
        elif pipeline.entrypoint.endswith('.nf'):
            pipeline.pipeline_type = ProtocolType.NEXTFLOW
            pipeline.save()


def revert(apps, _):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0046_pipeline_pipeline_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='config',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.RunPython(populate_pipeline_type, reverse_code=revert)
    ]
