# Generated by Django 2.2.24 on 2021-11-08 16:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0048_port_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='notify_for_outputs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=40, null=True), size=None),
        ),
    ]
