# Generated by Django 2.2.24 on 2022-01-13 17:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runner", "0049_run_resume_attempts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="run",
            name="notify_for_outputs",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=40, null=True), size=None
            ),
        ),
    ]
