# Generated by Django 2.2.24 on 2022-07-20 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0051_run_log_directory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='log_directory',
        ),
    ]
