# Generated by Django 2.2.28 on 2023-04-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_system', '0039_auto_20230410_0653'),
        ('runner', '0055_auto_20230112_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='requests',
            field=models.ManyToManyField(to='file_system.Request'),
        ),
    ]
