# Generated by Django 2.2.28 on 2023-03-24 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0055_auto_20230112_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='pipeline',
            name='pipeline_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='runner.PipelineName'),
        ),
    ]
