# Generated by Django 2.2.28 on 2023-04-11 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0056_run_requests'),
        ('runner', '0056_auto_20230328_0948'),
    ]

    operations = [
    ]
