# Generated by Django 2.2.28 on 2023-05-30 14:43

from django.db import migrations, models
import runner.models


class Migration(migrations.Migration):

    dependencies = [
        ("runner", "0057_auto_20230424_0743"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipeline",
            name="status",
            field=models.IntegerField(
                choices=[(0, "CWL"), (1, "NEXTFLOW")], db_index=True, default=runner.models.PipelineStatus(0)
            ),
        ),
    ]
