# Generated by Django 2.2.28 on 2024-06-13 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("runner", "0059_auto_20240610_1029"),
        ("runner", "0059_merge_20240605_1537"),
    ]

    operations = []
