# Generated by Django 2.2.28 on 2025-06-26 19:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("runner", "0065_port_extension"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipeline",
            name="profiles",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
    ]
