# Generated by Django 2.2.28 on 2025-08-13 20:38

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import runner.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('runner', '0066_pipeline_profiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorSDK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=False, max_length=100)),
                ('github', models.CharField(max_length=500)),
                ('version', models.CharField(default='main', max_length=50)),
                ('class_name', models.CharField(max_length=150)),
                ('package_name', models.CharField(max_length=1000)),
                ('active', models.BooleanField(default=False)),
                ('recipes_json', django.contrib.postgres.fields.jsonb.JSONField(default=list, null=True)),
                ('state', models.IntegerField(choices=[(0, 'REGISTER'), (1, 'INSTALL'), (2, 'READY'), (3, 'FAILED')], db_index=True, default=runner.models.ProtocolType(0))),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
