# Generated by Django 2.2.28 on 2025-07-31 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runner", "0066_pipeline_profiles"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipeline",
            name="user",
            field=models.CharField(default="kumarn1", max_length=100),
        ),
        migrations.AlterField(
            model_name="pipeline",
            name="config",
            field=models.TextField(blank=True, default=None, max_length=3000, null=True),
        ),
    ]
