# Generated by Django 2.2.24 on 2022-07-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runner", "0050_auto_20220113_1202"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="log_directory",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
