# Generated by Django 2.2.28 on 2023-01-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runner", "0054_pipeline_output_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="restart_attempts",
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name="run",
            name="resume_attempts",
            field=models.IntegerField(default=2),
        ),
    ]
