# Generated by Django 2.2.28 on 2024-05-01 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runner", "0057_auto_20230424_0743"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pipeline",
            name="config",
            field=models.CharField(blank=True, default=None, max_length=3000, null=True),
        ),
    ]
