# Generated by Django 2.2.28 on 2024-06-05 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("runner", "0058_auto_20231114_1310"),
        ("runner", "0058_auto_20240501_0133"),
    ]

    operations = []
