# Generated by Django 2.2.28 on 2025-03-31 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runner", "0063_auto_20250325_0802"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipeline",
            name="log_directory",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
