# Generated by Django 2.2.2 on 2019-09-25 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beagle_etl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etlerror',
            name='id',
        ),
        migrations.AddField(
            model_name='etlerror',
            name='basemodel_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='beagle_etl.BaseModel'),
            preserve_default=False,
        ),
    ]
