# Generated by Django 2.2.2 on 2019-09-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beagle_etl', '0002_auto_20190925_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='etlerror',
            name='type',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
