# Generated by Django 2.2.2 on 2019-09-30 18:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beagle_etl', '0004_auto_20190930_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='type',
        ),
        migrations.AlterField(
            model_name='job',
            name='args',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='message',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
