# Generated by Django 2.2.2 on 2019-10-07 21:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beagle_etl', '0007_job_lock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='args',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='children',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
