# Generated by Django 2.2.2 on 2019-11-07 20:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beagle_etl', '0008_auto_20191007_2149'),
    ]

    def insert_operator(apps, schema_editor):
        Operator = apps.get_model('beagle_etl', 'Operator')
        operator = Operator(active=False)
        operator.save()

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='callback',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='callback_args',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.RunPython(insert_operator),
    ]
