# Generated by Django 2.2.9 on 2020-02-24 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beagle_etl', '0013_auto_20200217_2200'),
        ('beagle_etl', '0013_auto_20200210_1902'),
    ]

    operations = [
    ]
