# Generated by Django 2.2.9 on 2020-03-12 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0001_initial'),
        ('beagle_etl', '0014_merge_20200224_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifier.JobGroup'),
        ),
    ]
