# Generated by Django 2.2.10 on 2020-05-15 03:43

import django.contrib.postgres.fields
from django.db import migrations, models


def add_assay_config(apps, _):
    Assay = apps.get_model('beagle_etl', 'Assay')

    a = Assay.objects.create(
        all=[
            "10X_Genomics_ATAC",
            "10X_Genomics_GeneExpression",
            "10X_Genomics_GeneExpression-3",
            "10X_Genomics_GeneExpression-5",
            "10X_Genomics_VDJ",
            "96Well_SmartSeq2",
            "Agilent_MouseAllExonV1",
            "AMBIGUOUS",
            "AmpliconSeq",
            "Archer-SolidTumorPanel",
            "ATACSeq",
            "ChIPSeq",
            "CRISPRScreen",
            "CRISPRSeq",
            "CustomCapture",
            "HemeBrainPACT",
            "HemePACT",
            "HemePACT_v4",
            "HumanWholeGenome",
            "IMPACT468",
            "MethylCaptureSeq",
            "M-IMPACT",
            "M-IMPACT_v1",
            "MSK-ACCESS_v1",
            "RNASeq",
            "RNASeq_PolyA",
            "RNASeq_RiboDeplete",
            "ShallowWGS",
            "SingleCellCNV",
            "SMARTerAmpSeq"
        ],
        disabled=[]
    )


class Migration(migrations.Migration):

    dependencies = [
        ('beagle_etl', '0015_job_job_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=None)),
                ('disabled', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=None)),
            ],
        ),
        migrations.RunPython(add_assay_config)
    ]
