# Generated by Django 2.2.10 on 2020-05-15 03:43

import django.contrib.postgres.fields
from django.db import migrations, models


def add_assay_config(apps, _):
    Assay = apps.get_model('beagle_etl', 'Assay')

    a = Assay.objects.create(
        all=[
          "Agilent_MouseAllExonV1",
          "Agilent_v4_51MB_Human",
          "HemePACT",
          "HemePACT_v3",
          "HemePACT_v4",
          "HumanWholeGenome",
          "IDT_Exome_v1_FP",
          "IMPACT+ (341 genes plus custom content)",
          "IMPACT341",
          "IMPACT410",
          "IMPACT468",
          "MSK-ACCESS_v1",
          "ShallowWGS",
          "WholeExomeSequencing",
          "WholeGenomeSequencing",
          "06605_F_Hg19",
          "07220_Hg19",
          "8050",
          "8390",
          "10X_Genomics_GeneExpression",
          "96Well_SmartSeq2",
          "AmpliconSeq",
          "AmpliSeq",
          "Archer-HemePanel",
          "Archer-Immunoverse",
          "Archer-SolidTumorPanel",
          "ATACSeq",
          "BRAINPACT_v1",
          "ChIPSeq",
          "CRISPRSceen",
          "CRISPRScreen",
          "CRISPRSeq",
          "CustomAmplificationPCR",
          "ddPCR",
          "HemeBrainPACT",
          "HemeBrainPACT_v1",
          "InDropSeq",
          "IonAmpliseqCancerHotspotv2",
          "IWG",
          "MethylCaptureSeq",
          "M-IMPACT",
          "M-IMPACT_v1",
          "MissionBio-Heme",
          "MouseWholeGenome",
          "PanCancerV2",
          "RNASeq",
          "RNASeq_PolyA",
          "RNASeq_RiboDeplete",
          "RRBS",
          "SingleCellCNV",
          "SMARTerAmpSeq",
          "Spo11Oligo",
          "WholeGenomeBisulfateSequencing"
        ],
        disabled=[
          "06605_F_Hg19",
          "07220_Hg19",
          "8050",
          "8390",
          "10X_Genomics_GeneExpression",
          "96Well_SmartSeq2",
          "AmpliconSeq",
          "AmpliSeq",
          "Archer-HemePanel",
          "Archer-Immunoverse",
          "Archer-SolidTumorPanel",
          "ATACSeq",
          "BRAINPACT_v1",
          "ChIPSeq",
          "CRISPRSceen",
          "CRISPRScreen",
          "CRISPRSeq",
          "CustomAmplificationPCR",
          "ddPCR",
          "HemeBrainPACT",
          "HemeBrainPACT_v1",
          "InDropSeq",
          "IonAmpliseqCancerHotspotv2",
          "IWG",
          "MethylCaptureSeq",
          "M-IMPACT",
          "M-IMPACT_v1",
          "MissionBio-Heme",
          "MouseWholeGenome",
          "PanCancerV2",
          "RNASeq",
          "RNASeq_PolyA",
          "RNASeq_RiboDeplete",
          "RRBS",
          "SingleCellCNV",
          "SMARTerAmpSeq",
          "Spo11Oligo",
          "WholeGenomeBisulfateSequencing"
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ('beagle_etl', '0015_job_job_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=None)),
                ('disabled', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=None)),
            ],
        ),
        migrations.RunPython(add_assay_config)
    ]
