# Generated by Django 2.2.11 on 2020-07-20 13:48

from django.db import migrations
from beagle_etl.jobs import TYPES
from beagle_etl.models import JobStatus


def remove_old_pool_normal_jobs(apps, _):
    Job = apps.get_model('beagle_etl', 'Job')

    failed_pool_normal_jobs = Job.objects.filter(run=TYPES['POOLED_NORMAL'], status=JobStatus.FAILED)
    for job in failed_pool_normal_jobs:
        if job.message.get('message', '').startswith('Invalid metadata runId'):
            print(job.id)
            print(job.message)
            job.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('beagle_etl', '0021_auto_20200616_1303'),
    ]

    operations = [
        migrations.RunPython(remove_old_pool_normal_jobs),
    ]
