# Generated by Django 2.2.11 on 2020-07-20 13:48

from django.db import migrations
from beagle_etl.jobs import TYPES


def remove_old_pool_normal_jobs(apps, _):
    # Changed because there is no more Job model
    Job = apps.get_model("beagle_etl", "Job")

    failed_pool_normal_jobs = Job.objects.filter(run=TYPES["POOLED_NORMAL"], status=4)
    for job in failed_pool_normal_jobs:
        if job.message.get("message", "").startswith("Invalid metadata runId"):
            print(job.id)
            print(job.message)
            job.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("beagle_etl", "0021_auto_20200616_1303"),
    ]

    operations = [
        # Disabled because there is no Job model anymore. Kept for reference
        # migrations.RunPython(remove_old_pool_normal_jobs),
    ]
