# Generated by Django 2.2.11 on 2020-08-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beagle_etl', '0025_auto_20200812_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='version',
            field=models.CharField(default=None, max_length=50, null=True),
            preserve_default=False,
        ),
    ]
