# Generated by Django 2.2.24 on 2022-05-11 22:38

import beagle_etl.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("notifier", "0014_auto_20211005_1636"),
        ("beagle_etl", "0032_auto_20220509_0718"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestCallbackJob",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="beagle_etl.BaseModel",
                    ),
                ),
                ("request_id", models.CharField(max_length=100)),
                ("recipe", models.CharField(max_length=100)),
                ("samples", django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "PENDING"), (1, "COMPLETED")],
                        db_index=True,
                        default=beagle_etl.models.SmileMessageStatus(0),
                    ),
                ),
                ("delay", models.IntegerField(default=0)),
                (
                    "job_group",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="notifier.JobGroup"
                    ),
                ),
                (
                    "job_group_notifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="notifier.JobGroupNotifier",
                    ),
                ),
            ],
            bases=("beagle_etl.basemodel",),
        ),
    ]
