# Generated by Django 2.2.28 on 2023-03-08 14:17
import json
from django.db import migrations
from django.conf import settings


def update_smile_messages(apps, schema_editor):
    SMILEMessage = apps.get_model('beagle_etl', 'SMILEMessage')
    for msg in SMILEMessage.objects.all():
        if msg.topic == settings.METADB_NATS_REQUEST_UPDATE:
            msg.request_id = json.loads(msg.message)[0].get(settings.REQUEST_ID_METADATA_KEY)
        elif msg.topic == settings.METADB_NATS_SAMPLE_UPDATE:
            msg.request_id = json.loads(msg.message)[0].get(settings.SAMPLE_ID_METADATA_KEY)
        msg.save()


class Migration(migrations.Migration):

    dependencies = [
        ('beagle_etl', '0035_validatormodel'),
    ]

    operations = [
        migrations.RunPython(update_smile_messages),
    ]
