# Generated by Django 2.2.28 on 2023-11-10 13:15

import django.contrib.postgres.fields
from django.db import migrations, models


def create_configuration_object(apps, _):
    SkipProject = apps.get_model("beagle_etl", "SkipProject")
    SkipProject.objects.create(skip_projects=[])


def remove_configuration_object(apps, _):
    SkipProject = apps.get_model("beagle_etl", "SkipProject")
    SkipProject.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("beagle_etl", "0037_auto_20230711_1028"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkipProject",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "skip_projects",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100), blank=True, null=True, size=None
                    ),
                ),
            ],
        ),
        migrations.RunPython(create_configuration_object, reverse_code=remove_configuration_object),
    ]
