# Generated by Django 2.2.28 on 2023-08-24 14:05

import beagle_etl.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beagle_etl", "0038_auto_20230824_0850"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smilemessage",
            name="status",
            field=models.IntegerField(
                choices=[(0, "PENDING"), (1, "IN_PROGRESS"), (2, "COMPLETED"), (3, "NOT_SUPPORTED"), (4, "FAILED")],
                db_index=True,
                default=beagle_etl.models.SmileMessageStatus(0),
            ),
        ),
    ]
