# Generated by Django 2.2.28 on 2025-06-09 21:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("beagle_etl", "0038_skipproject"),
    ]

    operations = [
        migrations.AddField(
            model_name="operator",
            name="recipes_json",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, null=True),
        ),
        migrations.AddField(
            model_name="requestcallbackjob",
            name="fastq_metadata",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
