# Generated by Django 2.2.28 on 2025-06-09 21:41

from django.db import migrations


def forwards(apps, schema_editor):
    Operator = apps.get_model("beagle_etl", "Operator")
    for op in Operator.objects.all():
        if op.recipes:
            op.recipes_json = [{"genePanel": op.recipes}]
        else:
            op.recipes_json = []
        op.save(update_fields=["recipes_json"])


class Migration(migrations.Migration):

    dependencies = [
        ("beagle_etl", "0039_auto_20250609_1724"),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
