# Generated by Django 2.2.28 on 2025-06-03 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beagle_etl', '0039_auto_20250603_1635'),
    ]

    operations = [
    ]
