# Generated by Django 2.2.28 on 2025-06-03 20:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beagle_etl', '0039_convert_operator_recipe_to_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='recipes_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='requestcallbackjob',
            name='start_meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='operator',
            name='recipes',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
