# Generated by Django 2.2.28 on 2024-01-12 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beagle_etl', '0038_skipproject'),
        ('beagle_etl', '0039_auto_20230824_1005'),
    ]

    operations = [
    ]
