# Generated by Django 2.2.28 on 2025-06-03 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beagle_etl', '0038_skipproject'),
    ]

    operations = [
    ]
