# Generated by Django 2.2.28 on 2025-09-03 14:15

import beagle_etl.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


def fix_statuses(apps, schema_editor):
    SMILEMessage = apps.get_model("beagle_etl", "SMILEMessage")
    for msg in SMILEMessage.objects.all():
        if msg.status >= 1:
            msg.status += 2
        msg.save(update_fields=("status",))

def revert(apps, schema_editor):
    SMILEMessage = apps.get_model("beagle_etl", "SMILEMessage")
    for msg in SMILEMessage.objects.all():
        if msg.status >= 3:
            msg.status -= 2
        msg.save(update_fields=("status",))

class Migration(migrations.Migration):

    dependencies = [
        ('beagle_etl', '0040_convert_operator_recipes_to_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='smilemessage',
            name='log',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='smilemessage',
            name='sample_status',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='smilemessage',
            name='status',
            field=models.IntegerField(choices=[(0, 'PENDING'), (1, 'IN_PROGRESS'), (2, 'COPY_FILES'), (3, 'COMPLETED'), (4, 'NOT_SUPPORTED'), (5, 'FAILED')], db_index=True, default=beagle_etl.models.SmileMessageStatus(0)),
        ),
        migrations.CreateModel(
            name='CopyFileTask',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='beagle_etl.BaseModel')),
                ('source', models.CharField(max_length=2000)),
                ('destination', models.CharField(max_length=2000)),
                ('status', models.IntegerField(choices=[(0, 'PENDING'), (1, 'COMPLETED'), (2, 'FAILED')], db_index=True, default=beagle_etl.models.CopyFileStatus(0))),
                ('smile_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beagle_etl.SMILEMessage')),
            ],
            bases=('beagle_etl.basemodel',),
        ),
        migrations.RunPython(fix_statuses, revert),
    ]
