# Generated by Django 2.2.28 on 2025-06-04 17:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beagle_etl', '0040_convert_operator_recipes_to_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='recipes_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, null=True),
        ),
    ]
