# Generated by Django 2.2.28 on 2025-06-05 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beagle_etl', '0041_auto_20250604_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestcallbackjob',
            old_name='meta_data',
            new_name='fastq_metadata',
        ),
    ]
