# Generated by Django 2.2.28 on 2025-09-05 11:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("notifier", "0015_auto_20240703_1411"),
        ("beagle_etl", "0041_auto_20250903_1015"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestcallbackjob",
            name="smile_message",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="beagle_etl.SMILEMessage"
            ),
        ),
        migrations.AddField(
            model_name="smilemessage",
            name="gene_panel",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="smilemessage",
            name="job_group",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="notifier.JobGroup"
            ),
        ),
        migrations.AddField(
            model_name="smilemessage",
            name="job_group_notifier",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="notifier.JobGroupNotifier"
            ),
        ),
        migrations.AlterField(
            model_name="smilemessage",
            name="log",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="smilemessage",
            name="sample_status",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.DeleteModel(
            name="Job",
        ),
    ]
