# Generated by Django 2.2.28 on 2026-02-10 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("beagle_etl", "0042_auto_20250905_0716"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CopyFileTask",
        ),
    ]
