# Generated by Django 2.2.28 on 2025-06-09 20:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beagle_etl', '0042_auto_20250605_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestcallbackjob',
            name='fastq_metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
