# Generated by Django 2.2.28 on 2026-02-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beagle_etl', '0043_delete_copyfiletask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smilemessage',
            name='log',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
