# Generated by Django 2.2.28 on 2026-02-20 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beagle_etl', '0044_auto_20260211_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validatormodel',
            name='basemodel_ptr',
        ),
        migrations.DeleteModel(
            name='NormalizerModel',
        ),
        migrations.DeleteModel(
            name='ValidatorModel',
        ),
    ]
