# Generated by Django 2.2.28 on 2026-02-25 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("beagle_etl", "0045_auto_20260220_0941"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SkipProject",
        ),
    ]
