# Generated by Django 6.0.4 on 2026-07-08 20:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beagle_etl", "0046_delete_skipproject"),
    ]

    operations = [
        migrations.AddField(
            model_name="smilemessage",
            name="retry_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="smilemessage",
            name="scheduled",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
