# Generated by Django 6.0.4 on 2026-07-08 20:56

import django.utils.timezone
from django.db import migrations, models


def set_scheduled_to_created_date(apps, schema_editor):
    SMILEMessage = apps.get_model("beagle_etl", "SMILEMessage")
    SMILEMessage.objects.update(scheduled=models.F("created_date"))


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("beagle_etl", "0046_delete_skipproject"),
    ]

    operations = [
        migrations.AddField(
            model_name="smilemessage",
            name="retry_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="smilemessage",
            name="scheduled",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RunPython(set_scheduled_to_created_date, noop),
    ]
