on: push

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5


    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install pip==19.3.1
        #pip install --force-reinstall 'setuptools<58.0.0'
        #pip install -r requirements.txt
        #pip install -r requirements-toil.txt
         pip install -r requirements-dev.txt
        #python manage.py migrate
    - name: Run migrations
      run: python manage.py migrate
    - name: Run test
      #run: python manage.py test
      run: |
        coverage run --source='.' manage.py test
        coverage report -m --fail-under=75
    #- name: Run flake8
      #uses: suo/flake8-github-action@releases/v1
     # with:
       #   checkName: 'build'   # NOTE: this needs to be the same as the job name
